name: aliah_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.7.0
  flutter_icons: ^1.0.0+1
  neumorphic: ^0.1.2
  url_launcher: ^5.4.2
  table_calendar: ^2.2.2
  page_transition: ^1.1.5
  bidirectional_scroll_view: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family:  AliahApp
      fonts:
        - asset: fonts/AliahApp.ttf